'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {api} from '../lib/client';
import {money,type State} from '../lib/data';

type Kind='automations'|'appointments'|'tickets'|'quotes';
type Item={description:string;quantity:number;unit_cents:number};
type RecordRow={id:string;created_at:string;title?:string;name?:string;contact_id?:string|null;assigned_to?:string|null;status?:string;notes?:string;description?:string;priority?:string;due_date?:string|null;starts_at?:string;ends_at?:string;location?:string;event?:string;stage?:string|null;task_title?:string;due_days?:number;enabled?:boolean;items?:Item[];tax_bps?:number;total_cents?:number;valid_until?:string|null};
const titles:Record<Kind,string>={automations:'Automation',appointments:'Appointment',tickets:'Ticket',quotes:'Quote'};
const statuses:Record<Kind,string[]>={automations:[],appointments:['scheduled','completed','cancelled'],tickets:['open','in_progress','resolved'],quotes:['draft','sent','accepted','declined']};
const label=(s:string)=>s.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
function download(name:string,type:string,content:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const csvCell=(v:unknown)=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';
function localTime(value?:string){const d=value?new Date(value):new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function Field({label:caption,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label>{caption}<input maxLength={300} {...props}/></label>;}
function Dialog({title,children,close,busy}:{title:string;children:React.ReactNode;close:()=>void;busy:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog className="business-dialog" ref={ref} onCancel={e=>{if(busy)e.preventDefault();else close();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" disabled={busy} onClick={close}>×</button></div>{children}</dialog>;}

export function BusinessModule({kind,workspace,workspaceName,data,canEdit,owner,refresh}:{kind:Kind;workspace:string;workspaceName:string;data:State;canEdit:boolean;owner:boolean;refresh:()=>Promise<void>}){
  const [rows,setRows]=useState<RecordRow[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[loading,setLoading]=useState(true);
  const [editor,setEditor]=useState<RecordRow|true|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [runs,setRuns]=useState<{id:string;rule_name:string;created_at:string}[]>([]);
  const [event,setEvent]=useState('contact_created'),[items,setItems]=useState<Item[]>([{description:'',quantity:1,unit_cents:0}]);
  const [defaultEnd]=useState(()=>new Date(Date.now()+3600000).toISOString());
  const [filter,setFilter]=useState('all');const version=useRef(0);
  const editable=kind==='automations'?owner:canEdit,base=`/business/${workspace}/${kind}`;
  const load=useCallback(async()=>{const request=++version.current;setLoading(true);try{const result=await api(`${base}?page=${page}`);if(request!==version.current)return;setRows(result.rows);setTotal(result.total);if(kind==='automations'){const history=await api(`/business/${workspace}/runs`);if(request===version.current)setRuns(history);}}catch(e){if(request===version.current)setNotice((e as Error).message);}finally{if(request===version.current)setLoading(false);}},[base,page,kind,workspace]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  function open(record:RecordRow|true){setNotice('');setEditor(record);setEvent(record===true?'contact_created':record.event||'contact_created');setItems(record===true?[{description:'',quantity:1,unit_cents:0}]:record.items?.map(i=>({...i}))||[]);}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor)return;const form=new FormData(e.currentTarget),values=Object.fromEntries(form);const body:Record<string,unknown>={...values};
    for(const k of ['contact_id','assigned_to','due_date','valid_until'])if(k in body)body[k]=body[k]||null;
    if(kind==='automations'){body.enabled=form.has('enabled');body.due_days=Number(values.due_days);body.stage=event==='contact_created'?null:values.stage;}
    if(kind==='appointments'){body.starts_at=new Date(String(values.starts_at)).toISOString();body.ends_at=new Date(String(values.ends_at)).toISOString();}
    if(kind==='quotes'){body.items=items;body.tax_bps=Math.round(Number(values.tax_bps)*100);}
    setBusy(true);try{await api(`${base}${editor===true?'':`/${editor.id}`}`,editor===true?'POST':'PATCH',body);setEditor(null);await Promise.all([load(),refresh()]);setNotice(`${titles[kind]} saved.`);}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}
  }
  async function remove(record:RecordRow){if(!confirm(`Delete this ${titles[kind].toLowerCase()}?`))return;setBusy(true);try{await api(`${base}/${record.id}`,'DELETE');setEditor(null);await load();setNotice('Record deleted.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  function printQuote(record:RecordRow){
    const person=data.contacts.find(c=>c.id===record.contact_id),popup=window.open('','_blank','width=850,height=900');if(!popup){setNotice('Allow the print window to open, then try again.');return;}
    const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
    popup.opener=null;popup.document.write(`<!doctype html><html><head><title>${esc(record.title)}</title><style>body{font:15px Arial;color:#233b37;max-width:760px;margin:48px auto;padding:20px}h1{color:#24705a}table{width:100%;border-collapse:collapse;margin:24px 0}td,th{text-align:left;border-bottom:1px solid #ddd;padding:12px}small{color:#666}p{white-space:pre-wrap}button{padding:12px}@media print{button{display:none}}</style></head><body><h1>${esc(workspaceName)}</h1><h2>${esc(record.title)}</h2><small>Quote ${esc(record.id)}</small><p>Customer: ${esc(person?.name||'Not linked')}<br>${esc(person?.company)}<br>${esc(person?.email)}</p><p>Status: ${esc(record.status)} · Valid until: ${esc(record.valid_until||'Not specified')}<br>Currency: USD</p><table><thead><tr><th>Description</th><th>Quantity</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>${record.items?.map(i=>`<tr><td>${esc(i.description)}</td><td>${i.quantity}</td><td>${esc((i.unit_cents/100).toFixed(2))}</td><td>${esc((i.quantity*i.unit_cents/100).toFixed(2))}</td></tr>`).join('')}</tbody></table><p>Tax: ${(record.tax_bps||0)/100}%</p><h2>Total: $${((record.total_cents||0)/100).toFixed(2)} USD</h2><p>${esc(record.notes)}</p></body></html>`);popup.document.close();const button=popup.document.createElement('button');button.textContent='Print / Save as PDF';button.onclick=()=>popup.print();popup.document.body.prepend(button);popup.focus();
  }
  function calendar(record:RecordRow){const escape=(v:string)=>v.replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll('\r','').replaceAll(',','\\,').replaceAll(';','\\;');const date=(v:string)=>new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');download('appointment.ics','text/calendar;charset=utf-8',`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//InTouch//CRM//EN\r\nBEGIN:VEVENT\r\nUID:${record.id}@intouch\r\nDTSTAMP:${date(new Date().toISOString())}\r\nDTSTART:${date(record.starts_at!)}\r\nDTEND:${date(record.ends_at!)}\r\nSUMMARY:${escape(record.title||'Appointment')}\r\nLOCATION:${escape(record.location||'')}\r\nDESCRIPTION:${escape(record.notes||'')}\r\nSTATUS:${record.status==='cancelled'?'CANCELLED':'CONFIRMED'}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`);}
  const current=editor===true||!editor?undefined:editor;
  const shown=rows.filter(r=>filter==='all'||(kind==='automations'?(r.enabled?'enabled':'disabled'):r.status)===filter);
  return <>
    <div className="workflow-toolbar"><button className="button secondary" disabled={loading||busy} onClick={()=>void load()}>Refresh</button>{editable&&<button className="button primary" onClick={()=>open(true)}>New {titles[kind].toLowerCase()}</button>}</div>
    {notice&&!editor&&<div className="notice" role="status">{notice}</div>}
    {kind==='automations'&&<p className="module-help">Rules create follow-up tasks when an event happens, including CSV imports. Existing records are not processed retroactively. Only owners manage rules. No emails or social messages are sent.</p>}
    {kind==='appointments'&&<p className="module-help">Times are shown in your device timezone ({Intl.DateTimeFormat().resolvedOptions().timeZone}). Assigned teammates cannot have overlapping scheduled appointments. Export an appointment to your calendar with its .ics file.</p>}
    {kind==='quotes'&&<p className="module-help">Build quotes in USD, print or save them as PDFs, and record their status manually. Marking a quote sent does not send an email.</p>}
    <section className="panel"><div className="section-heading"><h2>{label(kind)} <span className="soft-count">{total}</span></h2><label>Status on this page<select aria-label="Filter records" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option>{(kind==='automations'?['enabled','disabled']:statuses[kind]).map(s=><option value={s} key={s}>{label(s)}</option>)}</select></label></div>
    {loading?<div className="empty">Loading records…</div>:shown.length===0?<div className="empty">No {kind} match this page. {editable?'Create one to get started.':''}</div>:shown.map(r=><article key={r.id} className="business-row"><div><strong>{r.title||r.name}</strong><small>{kind==='automations'?`${r.event==='contact_created'?'New contact':`Deal enters ${r.stage}`} → ${r.task_title} · due in ${r.due_days} days`:data.contacts.find(c=>c.id===r.contact_id)?.name||'No linked contact'}</small>{r.assigned_to&&<small>{data.members.find(m=>m.user_id===r.assigned_to)?.email}</small>}{kind==='appointments'&&<small>{new Date(r.starts_at!).toLocaleString()} – {new Date(r.ends_at!).toLocaleString()} · {r.location||'No location'}</small>}{kind==='tickets'&&<small>{label(r.priority||'normal')} priority{r.due_date?` · Due ${r.due_date}`:''}</small>}{kind==='quotes'&&<small>${((r.total_cents||0)/100).toFixed(2)} USD · Valid until {r.valid_until||'not set'}</small>}</div><span className="status">{kind==='automations'?(r.enabled?'Enabled':'Paused'):label(r.status||'')}</span><div className="row-actions">{kind==='quotes'&&<button className="text-button" onClick={()=>printQuote(r)}>Print / PDF</button>}{kind==='appointments'&&<button className="text-button" onClick={()=>calendar(r)}>Calendar file</button>}<button className="text-button" onClick={()=>open(r)}>{editable?'Edit':'View'}</button></div></article>)}
    <div className="pagination"><button className="button secondary" disabled={page===0||loading||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} · 50 records per page</span><button className="button secondary" disabled={(page+1)*50>=total||loading||busy} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>
    {kind==='automations'&&<section className="panel workflow-panel run-history"><h2>Recent automation activity</h2>{runs.length?runs.map(r=><div className="activity" key={r.id}><strong>{r.rule_name}</strong><small>Follow-up created · {new Date(r.created_at).toLocaleString()}</small></div>):<p>No rules have run yet.</p>}<small>Latest 50 runs. Re-entering a stage creates a new follow-up; renaming a stage does not.</small></section>}
    {editor&&<Dialog title={`${editor===true?'New':editable?'Edit':'View'} ${titles[kind].toLowerCase()}`} busy={busy} close={()=>setEditor(null)}><form onSubmit={save} className="form-grid"><fieldset disabled={busy||!editable} className="business-fields">
      <Field label={kind==='automations'?'Rule name':'Title'} name={kind==='automations'?'name':'title'} defaultValue={current?.name||current?.title} maxLength={kind==='automations'?100:300} required/>
      {kind!=='automations'&&<label>Customer<select aria-label="Customer" name="contact_id" defaultValue={current?.contact_id||''}><option value="">No linked contact</option>{data.contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
      {kind!=='quotes'&&<label>Assigned teammate<select aria-label="Assigned teammate" name="assigned_to" defaultValue={current?.assigned_to||''}><option value="">Unassigned</option>{data.members.filter(m=>m.role!=='viewer').map(m=><option key={m.user_id} value={m.user_id}>{m.email}</option>)}</select></label>}
      {kind==='automations'?<><label>When<select aria-label="Automation event" name="event" value={event} onChange={e=>setEvent(e.target.value)}><option value="contact_created">A contact is created</option><option value="deal_stage_changed">A deal changes stage</option></select></label>{event==='deal_stage_changed'&&<label>Target stage<select aria-label="Target stage" name="stage" defaultValue={current?.stage||data.pipeline_stages[0]?.name} required>{data.pipeline_stages.map(s=><option key={s.name}>{s.name}</option>)}</select></label>}<Field label="Follow-up title" name="task_title" defaultValue={current?.task_title} required/><Field label="Days until due" name="due_days" type="number" min={0} max={365} defaultValue={current?.due_days??1} required/><label className="checkbox-field"><input name="enabled" type="checkbox" defaultChecked={current?.enabled??true}/>Enabled</label></>:<label>Status<select aria-label="Record status" name="status" defaultValue={current?.status||statuses[kind][0]}>{statuses[kind].map(s=><option value={s} key={s}>{label(s)}</option>)}</select></label>}
      {kind==='appointments'&&<><Field label="Starts at" name="starts_at" type="datetime-local" defaultValue={localTime(current?.starts_at)} required/><Field label="Ends at" name="ends_at" type="datetime-local" defaultValue={localTime(current?.ends_at||defaultEnd)} required/><Field label="Location or meeting link" name="location" defaultValue={current?.location}/></>}
      {kind==='tickets'&&<><label>Priority<select aria-label="Priority" name="priority" defaultValue={current?.priority||'normal'}>{['low','normal','high','urgent'].map(s=><option value={s} key={s}>{label(s)}</option>)}</select></label><Field label="Due date" name="due_date" type="date" defaultValue={current?.due_date||''}/><label>Description<textarea name="description" maxLength={5000} rows={5} defaultValue={current?.description}/></label></>}
      {kind==='quotes'&&<><div className="quote-items"><h3>Line items</h3>{items.map((item,i)=><div className="quote-line" key={i}><Field label={`Description ${i+1}`} value={item.description} required onChange={e=>setItems(v=>v.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/><Field label={`Quantity ${i+1}`} type="number" min={1} max={10000} step={1} value={item.quantity} required onChange={e=>setItems(v=>v.map((x,n)=>n===i?{...x,quantity:Number(e.target.value)}:x))}/><Field label={`Unit price USD ${i+1}`} type="number" min={0} max={10000000} step="0.01" value={item.unit_cents/100} required onChange={e=>setItems(v=>v.map((x,n)=>n===i?{...x,unit_cents:Math.round(Number(e.target.value)*100)}:x))}/><button type="button" className="text-button danger" disabled={items.length===1} onClick={()=>setItems(v=>v.filter((_,n)=>n!==i))}>Remove item {i+1}</button></div>)}<button type="button" className="button secondary" disabled={items.length>=50} onClick={()=>setItems(v=>[...v,{description:'',quantity:1,unit_cents:0}])}>Add line item</button><p>Subtotal: ${(items.reduce((n,i)=>n+i.quantity*i.unit_cents,0)/100).toFixed(2)} USD</p></div><Field label="Tax percent" name="tax_bps" type="number" min={0} max={100} step="0.01" defaultValue={(current?.tax_bps||0)/100} required/><Field label="Valid until" name="valid_until" type="date" defaultValue={current?.valid_until||''}/></>}
      {['appointments','quotes'].includes(kind)&&<label>Notes<textarea name="notes" maxLength={5000} rows={4} defaultValue={current?.notes}/></label>}
    </fieldset>{notice&&<p role="alert">{notice}</p>}{editable&&<div className="form-actions">{current&&<button type="button" disabled={busy} className="text-button danger" onClick={()=>void remove(current)}>Delete</button>}<button className="button primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></div>}</form></Dialog>}
  </>;
}

type Report={contacts:number;won_value:number;won_count:number;lost_count:number;overdue_tasks:number;resolved_tickets:number;pipeline:{name:string;kind:string;count:number;value:number}[];team:{email:string;role:string;open_tasks:number;overdue_tasks:number}[]};
export function Reports({workspace}:{workspace:string}){
  const today=new Date().toISOString().slice(0,10);const [from,setFrom]=useState(today.slice(0,8)+'01'),[to,setTo]=useState(today),[data,setData]=useState<Report|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const sequence=useRef(0);
  const load=useCallback(async()=>{const version=++sequence.current;setBusy(true);setData(null);setNotice('');try{const report=await api(`/business/${workspace}/reports?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`);if(version===sequence.current)setData(report);}catch(e){if(version===sequence.current)setNotice((e as Error).message);}finally{if(version===sequence.current)setBusy(false);}},[workspace,from,to]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  function exportReport(){if(!data)return;const rows:unknown[][]=[['InTouch sales report (USD)',from,to],['Metric','Value'],['New contacts',data.contacts],['Won deal value',data.won_value/100],['Won deals',data.won_count],['Lost deals',data.lost_count],['Current overdue follow-ups',data.overdue_tasks],['Resolved tickets',data.resolved_tickets],[],['Current pipeline stage','Deals','Value (USD)'],...data.pipeline.map(s=>[s.name,s.count,s.value/100]),[],['Teammate','Role','Open follow-ups','Overdue follow-ups'],...data.team.map(m=>[m.email,m.role,m.open_tasks,m.overdue_tasks])];download('intouch-report.csv','text/csv;charset=utf-8','\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'));}
  const closed=data?(data.won_count+data.lost_count):0,max=Math.max(1,...(data?.pipeline.map(s=>s.value)||[]));
  return <><section className="panel report-filters"><label>From<input aria-label="Report from" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input aria-label="Report to" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="button secondary" disabled={busy} onClick={()=>void load()}>Refresh report</button><button className="button primary" disabled={!data||busy} onClick={exportReport}>Export CSV</button></section>{notice&&<p role="alert">{notice}</p>}{busy&&<div className="empty">Calculating report…</div>}{data&&<><p className="module-help">Date range uses UTC. Won value is the value of deals currently marked won and closed during this period; it is not a payment ledger. Pipeline and workload show the current state.</p><div className="stats-grid">{[['New contacts',data.contacts],['Won deal value',money(data.won_value)],['Win rate',closed?`${Math.round(data.won_count/closed*100)}%`:'—'],['Overdue follow-ups',data.overdue_tasks],['Won / lost deals',`${data.won_count} / ${data.lost_count}`],['Resolved tickets',data.resolved_tickets]].map(([name,value])=><div className="stat-card" key={name}><div className="stat-top">{name}</div><div className="stat-value">{value}</div></div>)}</div><section className="panel workflow-panel report-chart"><h2>Current pipeline by stage</h2>{data.pipeline.map(s=><div className="report-bar" key={s.name}><div><strong>{s.name}</strong><span>{s.count} deals · {money(s.value)}</span></div><div className="bar-track"><div style={{width:`${s.value/max*100}%`}}/></div></div>)}</section><section className="panel workflow-panel run-history"><h2>Team workload</h2><div className="table-scroll"><table><thead><tr><th>Teammate</th><th>Role</th><th>Open follow-ups</th><th>Overdue</th></tr></thead><tbody>{data.team.map(m=><tr key={m.email}><td>{m.email}</td><td>{m.role}</td><td>{m.open_tasks}</td><td>{m.overdue_tasks}</td></tr>)}</tbody></table></div></section></>}</>;
}
