'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/client';
import type {Contact} from '../lib/data';
export function BirthdayFields({contact}:{contact?:Partial<Contact>}){
  return <fieldset className="birthday-fields"><legend>Birthday (optional)</legend><label>Birth month<select aria-label="Birth month" name="birth_month" defaultValue={contact?.birth_month??''}><option value="">Not provided</option>{['January','February','March','April','May','June','July','August','September','October','November','December'].map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><label>Birth day<input aria-label="Birth day" name="birth_day" type="number" min={1} max={31} defaultValue={contact?.birth_day??''}/></label><label>Birth year<input aria-label="Birth year" name="birth_year" type="number" min={1900} max={new Date().getFullYear()} placeholder="Optional" defaultValue={contact?.birth_year??''}/></label></fieldset>;
}
export function PreferredChannel({value='none'}:{value?:string}){return <label>Preferred contact channel<select aria-label="Preferred contact channel" name="preferred_channel" defaultValue={value}><option value="none">No preference</option><option value="email">Email</option><option value="phone">Phone call</option><option value="whatsapp">WhatsApp</option></select></label>;}
export function ConsentDetails({workspace,contact,canEdit}:{workspace:string;contact:Contact;canEdit:boolean}){
  type Consent={current:{marketing_email:boolean;marketing_whatsapp:boolean};events:{id:string;source:string;created_at:string;marketing_email:boolean;marketing_whatsapp:boolean;notice:{email?:string;whatsapp?:string;action?:string;submitted_at?:string}}[]};
  const [data,setData]=useState<Consent|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const path=`/registration/${workspace}/consent/${contact.id}`;
  useEffect(()=>{let live=true;api(path).then(result=>{if(live)setData(result);}).catch(e=>{if(live)setNotice(e.message);});return()=>{live=false;};},[path]);
  return <section className="contact-preferences"><h3>Birthday and preferences</h3><p>Birthday: {contact.birth_month?`${contact.birth_month}/${contact.birth_day}${contact.birth_year?`/${contact.birth_year}`:''}`:'Not provided'}</p><p>Preferred channel: {contact.preferred_channel==='none'?'No preference':contact.preferred_channel}</p><p>Preference alone does not authorize promotional messages.</p>{notice&&<p role="alert">{notice}</p>}{data&&<><p>Promotional email: <strong>{data.current.marketing_email?'Opted in':'Not opted in'}</strong><br/>Promotional WhatsApp: <strong>{data.current.marketing_whatsapp?'Opted in':'Not opted in'}</strong></p>{canEdit&&(data.current.marketing_email||data.current.marketing_whatsapp)&&<button className="text-button danger" disabled={busy} onClick={async()=>{if(!confirm('Withdraw all marketing consent for this contact?'))return;setBusy(true);try{await api(path,'PATCH');setData(await api(path));}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}>Withdraw marketing consent</button>}<details><summary>Consent history ({data.events.length})</summary>{data.events.length===0?<p>No consent has been recorded.</p>:data.events.map(e=><div className="activity" key={e.id}><strong>{e.source==='staff_withdrawal'?'Consent withdrawn':e.source==='contact_details_changed'?'Contact details changed':'Registration reviewed'}</strong><small>{new Date(e.created_at).toLocaleString()}</small><p>Email: {e.marketing_email?'yes':'no'} · WhatsApp: {e.marketing_whatsapp?'yes':'no'}</p>{e.notice.submitted_at&&<small>Submitted {new Date(e.notice.submitted_at).toLocaleString()}</small>}<small>{e.notice.email||e.notice.action}</small><small>{e.notice.whatsapp}</small></div>)}<small>Latest 50 events. Sending birthday messages is not enabled yet.</small></details></>}</section>;
}
