'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {BirthdayFields,PreferredChannel} from './customer-fields';
type PublicForm={business:string;title:string;description:string;revision:number;notice:{data:string;email:string;whatsapp:string;privacy_url:string}};
export default function PublicRegistration({token}:{token:string}){
  const [form,setForm]=useState<PublicForm|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[received,setReceived]=useState(false),[loaded,setLoaded]=useState(false);const requestId=useRef('');
  const endpoint=`${process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:4100'}/v1/public/registration/${encodeURIComponent(token)}`;
  useEffect(()=>{let live=true;requestId.current=crypto.randomUUID();fetch(endpoint,{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.message||'This form is unavailable.');if(live)setForm(data);}).catch(e=>{if(live)setNotice(e.message);}).finally(()=>{if(live)setLoaded(true);});return()=>{live=false;};},[endpoint]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!form)return;const f=new FormData(e.currentTarget),fields:Record<string,unknown>=Object.fromEntries(f);const website=fields.website;delete fields.website;for(const key of ['birth_month','birth_day','birth_year'])fields[key]=fields[key]?Number(fields[key]):null;for(const key of ['marketing_email','marketing_whatsapp','acknowledged'])fields[key]=f.has(key);setBusy(true);setNotice('');
    try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:requestId.current,revision:form.revision,website,fields})});const result=await response.json();if(!response.ok)throw Error(result.message||'Could not submit. Please try again.');setReceived(true);}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}
  }
  return <main className="registration-shell"><section className="panel registration-card"><div className="eyebrow">CUSTOMER REGISTRATION</div>{!loaded?<p>Loading form…</p>:received?<><h1>Thank you!</h1><p>Your information has been sent to {form?.business} for review. If you need to correct your details or change your preferences, please contact the business.</p></>:!form?<><h1>Form unavailable</h1><p>{notice}</p></>:<><p className="registration-business">{form.business}</p><h1>{form.title}</h1><p className="registration-intro">{form.description}</p><form className="form-grid" onSubmit={submit}><fieldset disabled={busy} className="business-fields"><label>Full name<input name="name" autoComplete="name" maxLength={300} required/></label><label>Email<input name="email" type="email" autoComplete="email" maxLength={254}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" placeholder="+15551234567" pattern="\+[1-9][0-9]{6,14}" maxLength={16}/></label><small>Provide at least an email or phone number. Include your country code in the phone number.</small><label>Company (optional)<input name="company" autoComplete="organization" maxLength={300}/></label><BirthdayFields/><PreferredChannel/><div className="form-honeypot" aria-hidden="true"><label>Website<input name="website" autoComplete="off" tabIndex={-1}/></label></div><fieldset className="marketing-choices"><legend>Marketing preferences (optional)</legend><label className="checkbox-field"><input type="checkbox" name="marketing_email"/>{form.notice.email}</label><label className="checkbox-field"><input type="checkbox" name="marketing_whatsapp"/>{form.notice.whatsapp}</label><small>You can register without agreeing to promotional messages.</small></fieldset><p className="data-notice">{form.notice.data}</p>{form.notice.privacy_url&&<a href={form.notice.privacy_url} target="_blank" rel="noopener noreferrer">Read the business privacy policy ↗</a>}<label className="checkbox-field"><input type="checkbox" name="acknowledged" required/>I understand that my details will be shared with {form.business} for its customer records.</label></fieldset>{notice&&<p role="alert" className="auth-notice">{notice}</p>}<button className="button primary" disabled={busy}>{busy?'Submitting…':'Submit my details'}</button></form></>}<footer>Powered by InTouch</footer></section></main>;
}
