'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import QRCode from 'react-qr-code';
import {api} from '../lib/client';
type Settings={id:string;title:string;description:string;privacy_url:string;enabled:boolean;revision:number;link:string};
type Submission={id:string;name:string;email:string;phone:string;company:string;birth_month:number|null;birth_day:number|null;birth_year:number|null;preferred_channel:string;marketing_email:boolean;marketing_whatsapp:boolean;created_at:string;status:string;consent_notice:{data:string;email:string;whatsapp:string};reviewed_at:string|null};
type Match={id:string;name:string;email:string;phone:string};
function ReviewDialog({children,close,busy}:{children:React.ReactNode;close:()=>void;busy:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="business-dialog" onCancel={e=>{if(busy)e.preventDefault();else close();}}><div className="modal-heading"><h2>Review customer registration</h2><button className="icon-button" aria-label="Close dialog" disabled={busy} onClick={close}>×</button></div>{children}</dialog>;}
export default function RegistrationManager({workspace,owner,canEdit,refresh}:{workspace:string;owner:boolean;canEdit:boolean;refresh:()=>Promise<void>}){
  const [settings,setSettings]=useState<Settings|null>(null),[rows,setRows]=useState<Submission[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[status,setStatus]=useState('pending');
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [selected,setSelected]=useState<Submission|null>(null),[matches,setMatches]=useState<Match[]>([]),[matching,setMatching]=useState(false),[customer,setCustomer]=useState(''),[verified,setVerified]=useState(false);
  const qr=useRef<HTMLDivElement>(null),version=useRef(0);const base=`/registration/${workspace}`;
  const load=useCallback(async()=>{const v=++version.current;setLoading(true);try{const results=await Promise.all([api(`${base}/submissions?page=${page}&status=${status}`),owner?api(`${base}/form`):Promise.resolve(null)]);if(v===version.current){setRows(results[0].rows);setTotal(results[0].total);setSettings(results[1]);}}catch(e){if(v===version.current)setNotice((e as Error).message);}finally{if(v===version.current)setLoading(false);}},[base,page,status,owner]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setNotice('');try{setSettings(await api(`${base}/form`,'POST',{title:f.get('title'),description:f.get('description'),privacy_url:f.get('privacy_url'),enabled:f.has('enabled')}));setNotice('Registration form saved.');}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}
  async function review(row:Submission){setSelected(row);setNotice('');setCustomer('');setVerified(false);setMatches([]);setMatching(true);try{setMatches(await api(`${base}/matches/${row.id}`));}catch(e){setNotice((e as Error).message);}finally{setMatching(false);}}
  async function approve(){if(!selected)return;setBusy(true);setNotice('');try{await api(`${base}/review/${selected.id}`,'POST',{existing_contact:customer||null,identity_verified:verified});setSelected(null);await Promise.all([load(),refresh()]);setNotice(customer?'Verified contact updated.':'Contact created from the reviewed registration.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  async function dismiss(row:Submission){if(!confirm('Dismiss this submission without changing a contact?'))return;setBusy(true);try{await api(`${base}/dismiss/${row.id}`,'POST');setSelected(null);await load();setNotice('Submission dismissed.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  function downloadQr(){const svg=qr.current?.querySelector('svg');if(!svg)return;const clone=svg.cloneNode(true) as SVGSVGElement;const size=svg.viewBox.baseVal.width;clone.setAttribute('viewBox',`-4 -4 ${size+8} ${size+8}`);clone.setAttribute('width','512');clone.setAttribute('height','512');const background=document.createElementNS('http://www.w3.org/2000/svg','rect');for(const [key,value]of Object.entries({x:'-4',y:'-4',width:String(size+8),height:String(size+8),fill:'#ffffff'}))background.setAttribute(key,value);clone.prepend(background);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='customer-registration-qr.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  if(!canEdit)return <section className="panel workflow-panel"><h2>Customer registration</h2><p>Only owners and members can review incoming customer information. Ask an owner to change your access if needed.</p></section>;
  return <>{notice&&!selected&&<div className="notice" role="status">{notice}</div>}{owner&&<section className="panel workflow-panel"><h2>Your customer registration form</h2><p>Share a link or QR code. Incoming details stay in a review queue until a teammate approves them.</p>{loading&&!settings?<p>Loading form settings…</p>:<div className="registration-settings"><form key={settings?.revision||'new'} className="form-grid" onSubmit={save}><fieldset disabled={busy} className="business-fields"><label>Form title<input name="title" maxLength={120} required defaultValue={settings?.title||'Customer registration'}/></label><label>Welcome message<textarea name="description" rows={3} maxLength={2000} defaultValue={settings?.description||'Share your details so we can stay in touch.'}/></label><label>Privacy policy URL (optional)<input name="privacy_url" type="url" maxLength={500} defaultValue={settings?.privacy_url||''} placeholder="https://your-business.com/privacy"/></label><label className="checkbox-field"><input name="enabled" type="checkbox" defaultChecked={settings?.enabled||false}/>Accept public registrations</label></fieldset><button className="button primary" disabled={busy}>Save form</button></form>{settings&&<div className="registration-share"><span className="status">{settings.enabled?'Accepting submissions':'Paused'}</span><label>Registration link<input readOnly value={settings.link} onFocus={e=>e.target.select()}/></label><div className="row-actions"><button className="text-button" onClick={()=>navigator.clipboard.writeText(settings.link).then(()=>setNotice('Link copied.')).catch(()=>setNotice('Select and copy the link above.'))}>Copy link</button><a className="text-button" href={settings.link} target="_blank" rel="noreferrer">Open form ↗</a></div><div className="registration-qr" ref={qr}><QRCode value={settings.link} size={192} level="M" title="Customer registration QR code"/></div><button className="button secondary" onClick={downloadQr}>Download QR code</button><button className="text-button danger" disabled={busy} onClick={async()=>{if(!confirm('Replace the registration link? Existing links and printed QR codes will stop working.'))return;setBusy(true);try{setSettings(await api(`${base}/rotate`,'POST'));setNotice('Link replaced. Share the new link and QR code.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}>Replace link</button>{new URL(settings.link).hostname==='127.0.0.1'&&<small>This link works on this computer only. Publish InTouch before sharing it with customers on other devices.</small>}</div>}</div>}</section>}
    <section className="panel run-history"><div className="section-heading"><h2>Customer submissions <span className="soft-count">{total}</span></h2><select aria-label="Submission status" value={status} onChange={e=>{setPage(0);setStatus(e.target.value);}}><option value="pending">Pending review</option><option value="accepted">Accepted</option><option value="dismissed">Dismissed</option></select><button className="text-button" disabled={busy||loading} onClick={()=>void load()}>Refresh submissions</button></div>{loading?<div className="empty">Loading submissions…</div>:!rows.length?<div className="empty">No {status} submissions.</div>:rows.map(row=><article className="business-row" key={row.id}><div><strong>{row.name}</strong><small>{row.email||row.phone}</small><small>{new Date(row.created_at).toLocaleString()} · {row.status}</small></div><button className="text-button" disabled={busy} onClick={()=>void review(row)}>{row.status==='pending'?'Review':'View submission'}</button></article>)}<div className="pagination"><button className="button secondary" disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} · 25 submissions per page</span><button className="button secondary" disabled={(page+1)*25>=total||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>
    {selected&&<ReviewDialog busy={busy} close={()=>setSelected(null)}><div className="submission-summary"><h3>{selected.name}</h3><p>{selected.email}<br/>{selected.phone}<br/>{selected.company}</p><p>Birthday: {selected.birth_month?`${selected.birth_month}/${selected.birth_day}${selected.birth_year?`/${selected.birth_year}`:''}`:'Not provided'}<br/>Preferred channel: {selected.preferred_channel}</p><p>Email marketing: <strong>{selected.marketing_email?'Opted in':'Not opted in'}</strong><br/>WhatsApp marketing: <strong>{selected.marketing_whatsapp?'Opted in':'Not opted in'}</strong></p><details><summary>Notice shown to the customer</summary><p>{selected.consent_notice.data}</p><p>{selected.consent_notice.email}</p><p>{selected.consent_notice.whatsapp}</p></details></div>{notice&&<p role="alert">{notice}</p>}{selected.status==='pending'&&<div className="form-grid"><p>Public submissions are not identity-verified. Review the details before creating a contact. To update an existing contact, verify the submission with that customer through a trusted channel first.</p>{matching?<p>Checking for matching contacts…</p>:matches.length>0?<><label>Matching contact<select aria-label="Matching contact" value={customer} onChange={e=>{setCustomer(e.target.value);setVerified(false);}}><option value="">Choose the verified customer</option>{matches.map(m=><option key={m.id} value={m.id}>{m.name} · {m.email||m.phone}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I verified with the customer that this submission belongs to them.</label><p>Applying this update replaces their supplied details and marketing choices. Unchecked marketing choices turn off consent.</p></>:<p>No matching email or phone was found. Approval will create a new contact.</p>}<div className="form-actions"><button className="text-button danger" disabled={busy||matching} onClick={()=>void dismiss(selected)}>Dismiss submission</button><button className="button primary" disabled={busy||matching||(matches.length>0&&(!customer||!verified))} onClick={()=>void approve()}>{customer?'Update verified contact':'Create contact'}</button></div></div>}</ReviewDialog>}
  </>;
}
