'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {api} from '../lib/client';
import type {Contact,Member,Stage} from '../lib/data';

export function Team({workspace,members,owner,refresh}:{workspace:string;members:Member[];owner:boolean;refresh:()=>Promise<void>}) {
  const [notice,setNotice]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false);
  const [invites,setInvites]=useState<{id:string;email:string;role:string;accepted_at:string|null;expires_at:string}[]>([]);
  const base=`/crm/${workspace}`;
  useEffect(()=>{let live=true;if(owner)api(`${base}/invitations`).then(x=>{if(live)setInvites(x);}).catch(e=>{if(live)setNotice(e.message);});return()=>{live=false;};},[base,owner]);
  async function run(path:string,method:string,body?:unknown){setBusy(true);setNotice('');try{const result=await api(path,method,body);await refresh();if(owner)setInvites(await api(`${base}/invitations`));return result;}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  return <section className="panel workflow-panel"><h2>Your team</h2><p>Owners manage access and stages. Members edit CRM records. Viewers have read-only access.</p>{notice&&<p role="alert">{notice}</p>}{members.map(m=><div className="task-row" key={m.user_id}><span><strong>{m.email}</strong><small>{m.role}</small></span>{owner&&m.role!=='owner'&&<><select aria-label={`Role for ${m.email}`} value={m.role} disabled={busy} onChange={e=>void run(`${base}/team/${m.user_id}`,'PATCH',{role:e.target.value})}><option value="member">Member</option><option value="viewer">Viewer</option></select><button className="text-button danger" disabled={busy} onClick={()=>{if(confirm(`Remove access for ${m.email}?`))void run(`${base}/team/${m.user_id}`,'PATCH',{role:null});}}>Remove</button></>}</div>)}{owner&&<><h3>Invite a teammate</h3><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const result=await run(`${base}/invitations`,'POST',Object.fromEntries(f));if(result)setLink(result.link);}}><label>Email<input name="email" type="email" required maxLength={254}/></label><label>Access<select aria-label="Access" name="role"><option value="member">Member</option><option value="viewer">Viewer</option></select></label><button className="button primary" disabled={busy}>Create invitation link</button></form><p>Share the link with your teammate. They must sign in with this verified email. Links expire after 7 days.</p>{link&&<div><label>Invitation link<input readOnly value={link} onFocus={e=>e.target.select()}/></label><button className="text-button" onClick={()=>navigator.clipboard.writeText(link).then(()=>setNotice('Link copied.')).catch(()=>setNotice('Select and copy the link above.'))}>Copy link</button></div>}{invites.filter(i=>!i.accepted_at).map(i=><div className="task-row" key={i.id}><span>{i.email}<small>{i.role} · Expires {new Date(i.expires_at).toLocaleDateString()}</small></span><button className="text-button danger" disabled={busy} onClick={()=>void run(`${base}/invitations/${i.id}`,'DELETE')}>Revoke</button></div>)}</>}</section>;
}

export function ContactDetails({workspace,contact,members,canEdit,email,owner}:{workspace:string;contact:Contact;members:Member[];canEdit:boolean;email:string;owner:boolean}) {
  type Note={id:string;body:string;kind:string;author_id:string;created_at:string};
  const [details,setDetails]=useState<{notes:Note[];activities:{id:string;summary:string;created_at:string}[]}>({notes:[],activities:[]});
  const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const base=`/crm/${workspace}/contacts/${contact.id}`;
  useEffect(()=>{let live=true;api(`${base}/detail`).then(d=>{if(live)setDetails(d);}).catch(e=>{if(live)setNotice(e.message);});return()=>{live=false;};},[base]);
  async function note(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);try{await api(`${base}/notes`,'POST',Object.fromEntries(new FormData(form)));setDetails(await api(`${base}/detail`));form.reset();}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}
  return <div className="contact-detail"><p>{contact.company} · {contact.status}</p><p>{contact.email} {contact.phone}</p>{contact.website&&<a href={contact.website} target="_blank" rel="noreferrer">{contact.website}</a>}<div className="tags">{contact.tags.map(t=><span className="status" key={t}>{t}</span>)}</div><p>Assigned to: {members.find(m=>m.user_id===contact.assigned_to)?.email||'Unassigned'}</p>{notice&&<p role="alert">{notice}</p>}{canEdit&&<form className="form-grid" onSubmit={note}><label>Activity type<select aria-label="Activity type" name="kind"><option value="note">Note</option><option value="call">Call</option><option value="meeting">Meeting</option></select></label><label>Notes<textarea name="body" required maxLength={5000} rows={4}/></label><button disabled={busy} className="button primary">Add note</button></form>}<h3>Notes and conversations</h3>{details.notes.length===0&&<p>No notes yet.</p>}{details.notes.map(n=><article className="activity" key={n.id}><small>{n.kind} · {new Date(n.created_at).toLocaleString()} · {members.find(m=>m.user_id===n.author_id)?.email||'Former teammate'}</small><p className="note-body">{n.body}</p>{canEdit&&(owner||members.find(m=>m.user_id===n.author_id)?.email===email)&&<button disabled={busy} className="text-button danger" onClick={async()=>{if(!confirm('Delete this note?'))return;setBusy(true);try{await api(`/crm/${workspace}/notes/${n.id}`,'DELETE');setDetails(await api(`${base}/detail`));}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}>Delete note</button>}</article>)}<h3>History</h3>{details.activities.map(a=><div className="activity" key={a.id}><strong>{a.summary}</strong><small>{new Date(a.created_at).toLocaleString()}</small></div>)}<small>Showing the latest 200 notes and history entries.</small></div>;
}

export function CsvImport({workspace,refresh}:{workspace:string;refresh:()=>Promise<void>}) {
  type Preview={rows:{name:string;email:string;company:string}[];errors:{row:number;message:string}[];duplicates:number;total:number;existingEmails:string[]};
  const [csv,setCsv]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  async function submit(commit:boolean){setBusy(true);setNotice('');try{const result=await api(`/crm/${workspace}/import`,'POST',{csv,commit});if(commit){await refresh();setPreview(null);setNotice(result.replayed?'This file was already imported.':`${result.inserted} contacts imported; ${result.skipped+result.fileDuplicates} duplicates skipped.`);}else setPreview(result);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  return <div className="form-grid"><p>CSV headers: name (required), email, phone, company, status, tags. Use Lead, Customer, or Inactive for status and | between tags. Maximum 500 contacts and 500 KB. Existing email addresses are skipped.</p><label>CSV file<input aria-label="CSV file" type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{setPreview(null);setNotice('');setCsv('');const file=e.target.files?.[0];if(!file)return;if(file.size>512000){setNotice('Choose a file smaller than 500 KB.');return;}setCsv(await file.text());}}/></label><button className="button secondary" disabled={busy||!csv} onClick={()=>void submit(false)}>Preview import</button>{notice&&<p role="status">{notice}</p>}{preview&&<><p>{preview.total} rows · {preview.duplicates} repeated emails in file · {preview.existingEmails.length} existing emails</p>{preview.errors.map((error,i)=><p role="alert" key={i}>Row {error.row}: {error.message}</p>)}<div className="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Company</th></tr></thead><tbody>{preview.rows.slice(0,20).map((r,i)=><tr key={i}><td>{r.name}</td><td>{r.email}</td><td>{r.company}</td></tr>)}</tbody></table></div><small>Preview shows the first 20 valid contacts.</small><button className="button primary" disabled={busy||preview.errors.length>0} onClick={()=>void submit(true)}>Import contacts</button></>}</div>;
}

export function StageSettings({workspace,stages,refresh}:{workspace:string;stages:Stage[];refresh:()=>Promise<void>}) {
  const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  async function save(e:FormEvent<HTMLFormElement>,old?:string){e.preventDefault();const form=e.currentTarget;const f=Object.fromEntries(new FormData(form));setBusy(true);try{await api(`/crm/${workspace}/stages${old?`/${encodeURIComponent(old)}`:''}`,old?'PATCH':'POST',{...f,position:Number(f.position)});await refresh();if(!old)form.reset();setNotice('Stages saved.');}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}
  return <div><p>Rename stages, choose their order, and mark them as open, won, or lost. Stages containing deals cannot be deleted.</p>{notice&&<p role="alert">{notice}</p>}{[...stages,null].map((s,i)=><form key={s?.name||'new'} className="stage-form form-grid" onSubmit={e=>void save(e,s?.name)}><h3>{s?'Edit stage':'Add stage'}</h3><label>Name<input name="name" required maxLength={50} defaultValue={s?.name}/></label><label>Order<input name="position" type="number" min={0} max={1000} required defaultValue={s?.position??i}/></label><label>Type<select aria-label="Activity type" name="kind" defaultValue={s?.kind||'open'}><option value="open">Open</option><option value="won">Won</option><option value="lost">Lost</option></select></label><div className="form-actions"><button className="button secondary" disabled={busy}>Save stage</button>{s&&<button type="button" className="text-button danger" disabled={busy||stages.length<=1} onClick={async()=>{if(!confirm(`Delete stage ${s.name}?`))return;setBusy(true);try{await api(`/crm/${workspace}/stages/${encodeURIComponent(s.name)}`,'DELETE');await refresh();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}>Delete stage</button>}</div></form>)}</div>;
}
